force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Father_Name__c.field-meta.xml
<CustomField>
    <fullName>Father_Name__c</fullName>
    <label>Father Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Map_2.cls
public class Map_2 {  
    
    public map<string,student__c> stdlist;
    public map<string,student__c> stdlist2;
    
    
    public Map_2(){   
        
            stdlist=new map<string,student__c>();
        
            list<student__c> newstdlist=new list<student__c>(); 
           
            newstdlist=[select id,name,Father_Name__c from student__c]; 
        
        for(student__c  Be:newstdlist){ 
                     
         stdlist.put(Be.name,Be);
            
        } 
        
        system.debug('stdlist=='+stdlist);
        
        
        
        
    /**
        if(stdlist2 !=null){ 
          system.debug('stdlist2=='+stdlist2);
        }
    **/
    
    }

}