force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Email_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Email Id</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Student__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Martch_23_Apex_Class.cls
public class Martch_23_Apex_Class { 
    
    @AuraEnabled
    public static list<student__c> stdlist(){ 
    
        return [select id,name,Email_Id__c,Gender__c	 from student__c];
     
    } 
    @AuraEnabled
    public static string  updatelist(list<student__c> studentlist){ 
        try{ 
        update studentlist;
         
        }catch(exception e){ 
           system.debug('exception s==='+e.getMessage());
        return 'update Faild...';
        } 
        return 'update Successfully...';

    }
}