force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INDIA</fullName>
            </value>
            <value>
                <fullName>UNITED STATES OF AMERICA</fullName>
            </value>
            <value>
                <fullName>SRI LANKA</fullName>
            </value>
            <value>
                <fullName>UNITED KINGDOM</fullName>
            </value>
            <value>
                <fullName>PAKISTAN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student__c/fields/Email_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Email Id</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/StudentApexClass.cls
public class StudentApexClass {
    
     
  
     @AuraEnabled
    public static list<student__c> getstdlist(){
      list<student__C> stdlist=[select id,name,DOB__c,Email_Id__c,Country__c  from student__C];
     return stdlist;
 
} 
        
     @AuraEnabled
    public static string updatestudents(list<student__c> stdlist){
     
        
        try{
            update stdlist;
            
            
            
        }catch(Exception e){
            System.debug('The following exception has occurred: ' + e.getMessage());
            return 'update Failed....';
            
        }
         return 'update successfully....';

    }
     
}