force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INDIA</fullName>
            </value>
            <value>
                <fullName>UNITED STATES OF AMERICA</fullName>
            </value>
            <value>
                <fullName>SRI LANKA</fullName>
            </value>
            <value>
                <fullName>UNITED KINGDOM</fullName>
            </value>
            <value>
                <fullName>PAKISTAN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student__c/fields/Total_amount_paid__c.field-meta.xml
<CustomField>
    <fullName>Total_amount_paid__c</fullName>
    <formula>IF( Total_Fee__c  ==  How_much_fee_paid__c , true,false)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total amount paid?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/March_4_mathod.cls
public class March_4_mathod { 
    
    public list<student__C> stlist; 
    public list<student__C> finalist;
    
    Public March_4_mathod(){ 
        
        stlist=[select id,name,country__c,Total_amount_paid__c from student__c ]; 
        system.debug('stlist=='+stlist); 
        
        
        finalist=new list<student__C>(); 
        
        for(student__C s:stlist){  
            
            if(s.country__c=='INDIA' && s.Total_amount_paid__c==true){
                system.debug('s=='+s);
                finalist.add(s);
            }
            
            
        }
        system.debug('FinalList=='+finalist);
    }
    
    
}