force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Email_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Email Id</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Augclass5.cls
public class Augclass5 {
    public string myname='saicharan';//Uday
    public boolean feepaid=true;      //false
    public student__c st;
    
    Public Augclass5(){ 
            method1();

           myclass mt =new myclass();
           system.debug('mt=='+mt);
           st=new student__c(Name='kumar',Email_Id__c='Email_Id__c');
           if(myname=='saicharan' && feepaid==false || st.Name=='kumar' ||mt.surname=='Bussa'&& mt.isFeepaid==true){
             
            system.debug('Condtion satisfied'); 
          }else{ 
            system.debug('Condtion Not satisfied'); 
          }
        
    }
    public void method1(){ 
        myname='uday'; 
        feepaid=false; 
        
    }
    public class myclass{ 
        public string surname='Bussa'; 
        public boolean isFeepaid=true;
    }
}