force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>INDIA</fullName>
            </value>
            <value>
                <fullName>UNITED STATES OF AMERICA</fullName>
            </value>
            <value>
                <fullName>SRI LANKA</fullName>
            </value>
            <value>
                <fullName>UNITED KINGDOM</fullName>
            </value>
            <value>
                <fullName>PAKISTAN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/New_list1.cls
public class New_list1 {   
    
        public list<student__c> std1 =new list <student__c>();
        public list<student__c>  std2 = new list<student__c>();
    
         
     
    public New_list1(){   
         std1=[select id,country__c from student__c where id='a002w00000FFRqN']; 
         std2=[select id,country__c from student__c where id='a002w00000FFRqN']; 
        
                 boolean be=std2.equals(std1);       
        
        system.debug('be=='+be);
            
           
    
    }
}