force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/course__c.field-meta.xml
<CustomField>
    <fullName>course__c</fullName>
    <label>course</label>
    <referenceTo>course__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Mar12_1.cls
public class Mar12_1 {
   public map<id,list<student__c>> stdlist; 
    
    public Mar12_1(){  
                
        stdlist=new map<id,list<student__c>>(); 
        list<course__c> clist=[select id,name,(select id,name from students__r)from course__c]; 
        
        for(course__c ce:clist){ 
            
            stdlist.put(ce.id,ce.students__r);  
            
        
        }
   
      
    system.debug('stdlist=='+stdlist);
    }
}