force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Batch__c.field-meta.xml
<CustomField>
    <fullName>Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Batch</label>
    <referenceTo>Batch__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Email_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Email Id</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Feb23_01class.cls
public class Feb23_01class {                  
    
    public string stname='charan'; 
    public string fname='balachander'; 
    public Integer salary=85000; 
    public Boolean salarypaid=false;  
    public student__c std;
    
    public Feb23_01class(){  
        
        method1(); 
        mycls m=new mycls(); 
        student__c std=new student__c(name='Arun kumar',Batch__c='a052w000003TdRC',Email_Id__c='saicharan.bs@gmail.com');
        
        if(stname=='Ccharan' || (fname=='balachander'&& salary==2500000)||m.std=='ramakrishnaa'||std.Email_Id__c=='saicharan.bs@gmail.comM'){  
        
        system.debug('Disply This,once The condition is satisfied');
        
        }else{ 
        
        system.debug('Disply This,once The condition is Not satisfied');
        }
        
        
    } 
    public void method1(){  
        
        stname='SSharan'; 
        salary=250000;
        
        
    }
    public class mycls{  
        public string std='ramakrishna';
        
        
    }
}