force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Email_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Id__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Email Id</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Feb22.cls
public class Feb22 {
    public string stname='Sai'; 
    public  Integer batch=25;  
    public Boolean isfeepaid=true; 
    public student__c std;
     
    
    
    
    public Feb22(){  
        Method1();  
        std =new student__c(name='Kiran',Email_Id__c='saicharan9032@gmail.com');
        mycls m=new mycls();
        if(stname=='sai' || (isfeepaid==true && batch>20 && m.std=='suryaa') || std.Email_Id__c=='saicharan9032@gmail.com'){
            
            system.debug('Display this,once the condition is satisfied'); 
            
        }else{
            system.debug('Display this,once the condition is Not satisfied');
        }
        
        
    } 
    
    public void method1(){
        
        stname='uday'; 
        batch=23; 
        isfeepaid=false;  
        
    }
    public class mycls{
        public string std='surya';
        
    }
}